# Generated by Django 5.2.5 on 2025-08-11 02:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('veterinarios', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='veterinario',
            name='especialidad',
            field=models.CharField(default='general', max_length=100),
            preserve_default=False,
        ),
    ]
